spring.application.name=spring-ai-ollama
# Ollama Server Base URL (Default is localhost:11434, only required if different)
spring.ai.ollama.base-url=http://localhost:11434
# Specify the Model Name (Crucial for Gemma 3), You can also use a specific tag like gemma3:7b or gemma3:2b if you pulled it.
#spring.ai.ollama.chat.options.model=gemma3:4b
spring.ai.ollama.chat.options.model=mistral

# Logging Configuration
logging.level.root=INFO
logging.level.controller.com.codelounge.agent.ai.AIController=DEBUG
# Set to DEBUG to see more details about the Spring AI internal workings
logging.level.org.springframework.ai=INFO